import os
import textwrap
from .urls_gen import camel_to_kebab

def generate_app_readme(app_name, models):
    """
    توليد ملف README_API.md لكل تطبيق لشرح الروابط والفلاتر المتاحة.
    """
    readme_file = os.path.join(app_name, 'README_API.md')
    
    models_info = ""
    for model in models:
        model_name = model.__name__
        url_route = camel_to_kebab(model_name)
        
        # جمع معلومات الحقول (اختياري للتبسيط)
        fields = [f.name for f in model._meta.get_fields() if f.concrete and not f.auto_created]
        
        models_info += f"### 📦 {model_name}\n"
        models_info += f"- **Base Endpoint**: `/{app_name}/{url_route}/`\n"
        models_info += f"- **Fields**: `{', '.join(fields[:5])}...`\n"
        models_info += f"- **Methods**: `GET (List/Retrieve)`, `POST (Create)`, `PUT/PATCH (Update)`, `DELETE`\n\n"

    content = textwrap.dedent(f"""
        # 📖 API Documentation: {app_name}

        هذا الملف تم توليده تلقائياً لشرح الـ APIs المتاحة في تطبيق `{app_name}`.

        ## 🚀 الموديلات المتاحة (Models)
        {models_info}

        ---

        ## 🔍 الفلترة والبحث (Filtering & Search)
        جميع الروابط تدعم العمليات التالية بشكل تلقائي:
        - **البحث**: استخدم `?search=كلمة_البحث` للبحث في الحقول النصية.
        - **الترتيب**: استخدم `?ordering=field_name` (أو `-field_name` للترتيب التنازلي).
        - **الفلترة**: يمكنك الفلترة مباشرة عبر الحقول، مثال: `?status=active`.

        ## 🎯 الحقول الديناميكية (Dynamic Fields)
        لتحسين الأداء، يمكنك اختيار حقول محددة فقط في الاستجابة:
        `GET /{app_name}/model_name/?fields=id,name,email`

        ---
        *Generated by [django-auto-api-gen](https://github.com/Amer-Tawfiq/django-auto-api-gen)*
    """).lstrip()
    
    with open(readme_file, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"✅ Generated README_API: {readme_file}")
